name: customer_app
description: 22850034 Advanced Software Design - Customer App
version: 1.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.6.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  flutter_animarker: ^3.2.0
  google_maps_flutter_web: ^0.5.1
  google_maps_flutter: ^2.3.1
  google_polyline_algorithm: ^3.1.0
  geolocator: ^9.0.2
  flutter_svg: ^2.0.7
  flutter_rating_bar: ^4.0.1
  lottie: ^2.4.0
  shimmer: ^3.0.0
  google_maps_webservice:
    git:
      url: https://github.com/YakivGalkin/google_maps_webservice

  uuid: ^3.0.5

  touch_indicator: ^2.0.0
  url_launcher: ^6.0.20

  http: ^0.13.3
  intl: ^0.17.0
  flutter_dotenv: ^5.0.2
  socket_io_client: ^2.0.0
  logger: ^1.0.0

  shared_preferences: ^2.0.8

dev_dependencies:
  chewie_audio: ^1.5.0

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/markers/
    - assets/lottie/
    - .env
